apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: roboshop

spec:
  selector:
    project: roboshop
    component: catalogue
    environment: dev

  ports:
  - protocol: TCP
    port: 80
    targetport: 80

