apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    project: roboshop
    purpose: rs-demo
    tier: frontend
    component: frontend

spec:
  replicas: 3
  selector:
     matchLabels:
      project: roboshop
      purpose: rs-demo
      tier: frontend
      component: frontend

  template:
    metadata:
      labels:
        project: roboshop
        purpose: rs-demo
        tier: frontend
        component: frontend
    spec:
      containers:
      - name: nginx
        image: nginx 
